#01: Menyertakan Prefix dan Suffix pada seluruh Kolom Data Frame

Import Modules

In [23]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.3.5

Persiapan Data Frame

In [24]:
n_rows = 5
n_cols = 5
cols = tuple('ABCDE')

df = pd.DataFrame(np.random.randint(1, 10, size=(n_rows, n_cols)), 
                  columns=cols)
df

   A  B  C  D  E
0  3  8  4  7  9
1  6  7  9  5  1
2  5  6  3  6  5
3  4  4  9  5  6
4  5  3  5  6  7

In [25]:
tuple('ABCDE')

('A', 'B', 'C', 'D', 'E')

Menyertakan Prefix Kolom

In [26]:
df.add_prefix('kolom_')

   kolom_A  kolom_B  kolom_C  kolom_D  kolom_E
0        3        8        4        7        9
1        6        7        9        5        1
2        5        6        3        6        5
3        4        4        9        5        6
4        5        3        5        6        7

Menyertakan Suffix Kolom

In [27]:
df.add_suffix('_field')

   A_field  B_field  C_field  D_field  E_field
0        3        8        4        7        9
1        6        7        9        5        1
2        5        6        3        6        5
3        4        4        9        5        6
4        5        3        5        6        7

#02: Pemilihan baris (rows selection) pada Data Frame

Persiapan Data Frame

In [28]:
n_rows = 10
n_cols = 5
cols = tuple('ABCDE')

df = pd.DataFrame(np.random.randint(1, 5, size=(n_rows, n_cols)), 
                  columns=cols)
df

   A  B  C  D  E
0  3  2  1  1  4
1  3  1  2  3  1
2  2  1  1  3  2
3  4  1  2  2  3
4  1  1  3  3  4
5  3  3  4  3  4
6  1  3  2  1  1
7  3  2  3  4  1
8  2  3  4  1  3
9  1  3  1  3  4

Selection dengan operator logika |

In [29]:
df[(df['A'] == 1) | (df['A'] == 3)]

   A  B  C  D  E
0  3  2  1  1  4
1  3  1  2  3  1
4  1  1  3  3  4
5  3  3  4  3  4
6  1  3  2  1  1
7  3  2  3  4  1
9  1  3  1  3  4

Selection dengan fungsi isin()

In [30]:
df[df['A'].isin([1, 3])]

   A  B  C  D  E
0  3  2  1  1  4
1  3  1  2  3  1
4  1  1  3  3  4
5  3  3  4  3  4
6  1  3  2  1  1
7  3  2  3  4  1
9  1  3  1  3  4

Mengenal operator negasi ~

In [31]:
df[~df['A'].isin([1, 3])]

   A  B  C  D  E
2  2  1  1  3  2
3  4  1  2  2  3
8  2  3  4  1  3

#03: Konversi tipe data String ke Numerik pada kolom Data Frame

Persiapan Data Frame

In [32]:
data = {'col1':['1', '2', '3', 'teks'], 
        'col2':['1', '2', '3', '4']}

df = pd.DataFrame(data)
df

   col1 col2
0     1    1
1     2    2
2     3    3
3  teks    4

In [33]:
df.dtypes

col1    object
col2    object
dtype: object

Konversi tipe data dengan fungsi astype()

In [34]:
df_x = df.astype({'col2':'int'})
df_x

   col1  col2
0     1     1
1     2     2
2     3     3
3  teks     4

In [35]:
df_x.dtypes

col1    object
col2     int64
dtype: object

Konversi tipe data numerik dengan fungsi to_numeric()

In [36]:
df.apply(pd.to_numeric, errors='coerce')

   col1  col2
0   1.0     1
1   2.0     2
2   3.0     3
3   NaN     4

#04: Pemilihan kolom (columns selection) pada Data Frame berdasarkan tipe data

Persiapan Data Frame

In [37]:
n_rows = 5
n_cols = 2
cols = ['bil_pecahan', 'bil_bulat']

df = pd.DataFrame(np.random.randint(1, 20, size=(n_rows, n_cols)), columns=cols)

df['bil_pecahan'] = df['bil_pecahan'].astype('float')

df.index = pd.date_range(start='2024-10-01', periods=n_rows, freq='h')

df = df.reset_index()
df['teks'] = list('ABCDE')

df

                index  bil_pecahan  bil_bulat teks
0 2024-10-01 00:00:00          6.0         13    A
1 2024-10-01 01:00:00         15.0          9    B
2 2024-10-01 02:00:00         19.0          4    C
3 2024-10-01 03:00:00         10.0         11    D
4 2024-10-01 04:00:00          3.0         19    E

In [45]:
df.dtypes

index          datetime64[ns]
bil_pecahan           float64
bil_bulat               int32
teks                   object
dtype: object

Memilih kolom bertipe data numerik

In [39]:
df.select_dtypes(include='number')

   bil_pecahan  bil_bulat
0          6.0         13
1         15.0          9
2         19.0          4
3         10.0         11
4          3.0         19

In [ ]:
df.select_dtypes(include='float')

   bil_pecahan
0          6.0
1         15.0
2         19.0
3         10.0
4          3.0

In [41]:
df.select_dtypes(include='int')

   bil_bulat
0         13
1          9
2          4
3         11
4         19

Memilih kolom bertipe data string atau object

In [42]:
df.select_dtypes(include='object')

  teks
0    A
1    B
2    C
3    D
4    E

Memilih kolom bertipe data datetime

In [43]:
df.select_dtypes(include='datetime')

                index
0 2024-10-01 00:00:00
1 2024-10-01 01:00:00
2 2024-10-01 02:00:00
3 2024-10-01 03:00:00
4 2024-10-01 04:00:00

Memilih kolom dengan kombinasi tipe data

In [44]:
df.select_dtypes(include=['number', 'object'])

   bil_pecahan  bil_bulat teks
0          6.0         13    A
1         15.0          9    B
2         19.0          4    C
3         10.0         11    D
4          3.0         19    E